version: '3'

services:
  nodejs:
    container_name: cluster0-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
